### ISSUE TITLE
Broken name

### ISSUE THREAD

**Issue by filipesn** [VictiniX888/self-governing-catalyst#1]
the name and the gui names are broken

**Comment by ghost** [comment]
For context
![image](https://user-images.githubusercontent.com/918422/90463392-28958980-e10b-11ea-98de-98c178a2f9d3.png)

This is on 1.16.2 with selfgoverningcatalyst-1.16-1.0.3.jar
I think it's a missing or broken lang file.

**Comment by VictiniX888** [comment]
Thanks for the issue report! Yes, the lang file was indeed broken; luckily this should be an easy fix.
