### ISSUE TITLE
Suggestion: an option to have the catalyst interact with another side of the target block

### ISSUE THREAD

**Issue by ghost** [VictiniX888/self-governing-catalyst#2]
For instance, placing the catalyst under a block, pointing up.  In its inventory it would have NESWUP buttons.  If the N button is pressed, the catalyst would interact with the North side of the block instead of the bottom.

**Comment by VictiniX888** [comment]
Personally I think a part of using this machine is the puzzle to place it in a specific way such that it interacts with the block in the way you want it to. Or at least that's what I thought when I used the Autonomous Activator/Mechanical User. Those didn't have such options either for what it's worth.

**Comment by ghost** [comment]
Fair enough. :-)  Thanks for reading!
